// Code generated by mockery v2.33.2. DO NOT EDIT.

package main

import (
	image "image"
	color "image/color"

	mock "github.com/stretchr/testify/mock"

	tag "github.com/formicidae-tracker/tag-layouter/internal/tag"
)

// MockVectorDrawer is an autogenerated mock type for the VectorDrawer type
type MockVectorDrawer struct {
	mock.Mock
}

type MockVectorDrawer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVectorDrawer) EXPECT() *MockVectorDrawer_Expecter {
	return &MockVectorDrawer_Expecter{mock: &_m.Mock}
}

// DrawPolygons provides a mock function with given fields: _a0
func (_m *MockVectorDrawer) DrawPolygons(_a0 []tag.Polygon) {
	_m.Called(_a0)
}

// MockVectorDrawer_DrawPolygons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DrawPolygons'
type MockVectorDrawer_DrawPolygons_Call struct {
	*mock.Call
}

// DrawPolygons is a helper method to define mock.On call
//   - _a0 []tag.Polygon
func (_e *MockVectorDrawer_Expecter) DrawPolygons(_a0 interface{}) *MockVectorDrawer_DrawPolygons_Call {
	return &MockVectorDrawer_DrawPolygons_Call{Call: _e.mock.On("DrawPolygons", _a0)}
}

func (_c *MockVectorDrawer_DrawPolygons_Call) Run(run func(_a0 []tag.Polygon)) *MockVectorDrawer_DrawPolygons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]tag.Polygon))
	})
	return _c
}

func (_c *MockVectorDrawer_DrawPolygons_Call) Return() *MockVectorDrawer_DrawPolygons_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVectorDrawer_DrawPolygons_Call) RunAndReturn(run func([]tag.Polygon)) *MockVectorDrawer_DrawPolygons_Call {
	_c.Call.Return(run)
	return _c
}

// DrawRectangle provides a mock function with given fields: _a0, _a1
func (_m *MockVectorDrawer) DrawRectangle(_a0 image.Rectangle, _a1 color.Gray) {
	_m.Called(_a0, _a1)
}

// MockVectorDrawer_DrawRectangle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DrawRectangle'
type MockVectorDrawer_DrawRectangle_Call struct {
	*mock.Call
}

// DrawRectangle is a helper method to define mock.On call
//   - _a0 image.Rectangle
//   - _a1 color.Gray
func (_e *MockVectorDrawer_Expecter) DrawRectangle(_a0 interface{}, _a1 interface{}) *MockVectorDrawer_DrawRectangle_Call {
	return &MockVectorDrawer_DrawRectangle_Call{Call: _e.mock.On("DrawRectangle", _a0, _a1)}
}

func (_c *MockVectorDrawer_DrawRectangle_Call) Run(run func(_a0 image.Rectangle, _a1 color.Gray)) *MockVectorDrawer_DrawRectangle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Rectangle), args[1].(color.Gray))
	})
	return _c
}

func (_c *MockVectorDrawer_DrawRectangle_Call) Return() *MockVectorDrawer_DrawRectangle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVectorDrawer_DrawRectangle_Call) RunAndReturn(run func(image.Rectangle, color.Gray)) *MockVectorDrawer_DrawRectangle_Call {
	_c.Call.Return(run)
	return _c
}

// EndTranslate provides a mock function with given fields:
func (_m *MockVectorDrawer) EndTranslate() {
	_m.Called()
}

// MockVectorDrawer_EndTranslate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTranslate'
type MockVectorDrawer_EndTranslate_Call struct {
	*mock.Call
}

// EndTranslate is a helper method to define mock.On call
func (_e *MockVectorDrawer_Expecter) EndTranslate() *MockVectorDrawer_EndTranslate_Call {
	return &MockVectorDrawer_EndTranslate_Call{Call: _e.mock.On("EndTranslate")}
}

func (_c *MockVectorDrawer_EndTranslate_Call) Run(run func()) *MockVectorDrawer_EndTranslate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVectorDrawer_EndTranslate_Call) Return() *MockVectorDrawer_EndTranslate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVectorDrawer_EndTranslate_Call) RunAndReturn(run func()) *MockVectorDrawer_EndTranslate_Call {
	_c.Call.Return(run)
	return _c
}

// Label provides a mock function with given fields: p, s, size, c
func (_m *MockVectorDrawer) Label(p image.Point, s string, size int, c color.Gray) {
	_m.Called(p, s, size, c)
}

// MockVectorDrawer_Label_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Label'
type MockVectorDrawer_Label_Call struct {
	*mock.Call
}

// Label is a helper method to define mock.On call
//   - p image.Point
//   - s string
//   - size int
//   - c color.Gray
func (_e *MockVectorDrawer_Expecter) Label(p interface{}, s interface{}, size interface{}, c interface{}) *MockVectorDrawer_Label_Call {
	return &MockVectorDrawer_Label_Call{Call: _e.mock.On("Label", p, s, size, c)}
}

func (_c *MockVectorDrawer_Label_Call) Run(run func(p image.Point, s string, size int, c color.Gray)) *MockVectorDrawer_Label_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Point), args[1].(string), args[2].(int), args[3].(color.Gray))
	})
	return _c
}

func (_c *MockVectorDrawer_Label_Call) Return() *MockVectorDrawer_Label_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVectorDrawer_Label_Call) RunAndReturn(run func(image.Point, string, int, color.Gray)) *MockVectorDrawer_Label_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateScale provides a mock function with given fields: _a0, _a1
func (_m *MockVectorDrawer) TranslateScale(_a0 image.Point, _a1 int) {
	_m.Called(_a0, _a1)
}

// MockVectorDrawer_TranslateScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateScale'
type MockVectorDrawer_TranslateScale_Call struct {
	*mock.Call
}

// TranslateScale is a helper method to define mock.On call
//   - _a0 image.Point
//   - _a1 int
func (_e *MockVectorDrawer_Expecter) TranslateScale(_a0 interface{}, _a1 interface{}) *MockVectorDrawer_TranslateScale_Call {
	return &MockVectorDrawer_TranslateScale_Call{Call: _e.mock.On("TranslateScale", _a0, _a1)}
}

func (_c *MockVectorDrawer_TranslateScale_Call) Run(run func(_a0 image.Point, _a1 int)) *MockVectorDrawer_TranslateScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Point), args[1].(int))
	})
	return _c
}

func (_c *MockVectorDrawer_TranslateScale_Call) Return() *MockVectorDrawer_TranslateScale_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVectorDrawer_TranslateScale_Call) RunAndReturn(run func(image.Point, int)) *MockVectorDrawer_TranslateScale_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVectorDrawer creates a new instance of MockVectorDrawer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVectorDrawer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVectorDrawer {
	mock := &MockVectorDrawer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
